[package]
name = "occult"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Teach your code to use magic"

[dependencies]

[dev-dependencies]
tokio = { version = "1.42.0", features = ["rt", "macros"] }
